###服务端口号
server:
  port: 8100
###eureka 基本信息配置
eureka:
  instance:
    prefer-ip-address: true
    ###注册到eurekaip地址
  client:
    serviceUrl:
      defaultZone: http://192.168.239.111:8100/eureka/,http://192.168.239.7:8100/eureka/,http://192.168.239.9:8100/eureka
    ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: true

spring:
  application:
    name: eureka
  cloud:
    inetutils:
      preferred-networks[0]: 192.168